export const messages = {
  USER_SAVE: 'User save',
  USER_FOUND: 'User found',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXIST: 'User already exist with id',
  USER_UPDATED: 'User updated',
  USER_DELETE: 'User deleted',
  POST_NOT_FOUND: 'Post not found',
  POST_CREATE: 'Post created successfully',
  POST_UPDATE: 'Post updated successfully',
  POST_DELETE: 'Post deleted successfully',
  COMMENT_ADDED: 'Comment added successfully!',
  COMMENT_UPDATED: 'Comment updated successfully!',
  COMMENT_DELETED: 'Comment deleted successfully!',
  COMMENT_NOT_FOUND: 'Comment not found',
  SOMETHING_WENT_WRONG: 'Something went wrong.',
  UNKNOWN_ERROR: 'An unknown error occurred',
  POST_LIKED: 'Post liked',
  POST_DISLIKED: 'Post disliked',
};
